spring:
  datasource:
    url: jdbc:h2:mem:boxdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      defer-datasource-initialization: true
      mode: always
      continue-on-error: true

server:
  port: 8080
